-- Creates or stabilizes the RFQ marketplace schema used by Monate Connect.
-- The live application already uses numeric RFQ IDs for quote, award, and route
-- references, so this migration keeps that contract and adds the marketplace
-- fields required by the seeded procurement data.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS public.rfqs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  scope TEXT,
  buyer_name TEXT,
  buyer_org TEXT,
  buyer_user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  industry TEXT,
  provinces TEXT[] DEFAULT '{}',
  bbbee_requirement TEXT,
  estimated_value_min NUMERIC,
  estimated_value_max NUMERIC,
  closing_date TIMESTAMPTZ,
  published_date TIMESTAMPTZ DEFAULT NOW(),
  status TEXT DEFAULT 'open',
  require_csd BOOLEAN DEFAULT TRUE,
  require_tax_clearance BOOLEAN DEFAULT TRUE,
  require_vat BOOLEAN DEFAULT FALSE,
  is_public BOOLEAN DEFAULT TRUE,
  quote_count INTEGER DEFAULT 0,
  category TEXT,
  province TEXT,
  region TEXT,
  budget TEXT,
  deadline DATE,
  created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  is_demo BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.rfqs ADD COLUMN IF NOT EXISTS scope TEXT;
ALTER TABLE public.rfqs ADD COLUMN IF NOT EXISTS buyer_name TEXT;
ALTER TABLE public.rfqs ADD COLUMN IF NOT EXISTS buyer_org TEXT;
ALTER TABLE public.rfqs ADD COLUMN IF NOT EXISTS buyer_user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.rfqs ADD COLUMN IF NOT EXISTS industry TEXT;
ALTER TABLE public.rfqs ADD COLUMN IF NOT EXISTS provinces TEXT[] DEFAULT '{}';
ALTER TABLE public.rfqs ADD COLUMN IF NOT EXISTS bbbee_requirement TEXT;
ALTER TABLE public.rfqs ADD COLUMN IF NOT EXISTS estimated_value_min NUMERIC;
ALTER TABLE public.rfqs ADD COLUMN IF NOT EXISTS estimated_value_max NUMERIC;
ALTER TABLE public.rfqs ADD COLUMN IF NOT EXISTS closing_date TIMESTAMPTZ;
ALTER TABLE public.rfqs ADD COLUMN IF NOT EXISTS published_date TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE public.rfqs ADD COLUMN IF NOT EXISTS require_csd BOOLEAN DEFAULT TRUE;
ALTER TABLE public.rfqs ADD COLUMN IF NOT EXISTS require_tax_clearance BOOLEAN DEFAULT TRUE;
ALTER TABLE public.rfqs ADD COLUMN IF NOT EXISTS require_vat BOOLEAN DEFAULT FALSE;
ALTER TABLE public.rfqs ADD COLUMN IF NOT EXISTS is_public BOOLEAN DEFAULT TRUE;
ALTER TABLE public.rfqs ADD COLUMN IF NOT EXISTS quote_count INTEGER DEFAULT 0;
ALTER TABLE public.rfqs ADD COLUMN IF NOT EXISTS category TEXT;
ALTER TABLE public.rfqs ADD COLUMN IF NOT EXISTS province TEXT;
ALTER TABLE public.rfqs ADD COLUMN IF NOT EXISTS region TEXT;
ALTER TABLE public.rfqs ADD COLUMN IF NOT EXISTS budget TEXT;
ALTER TABLE public.rfqs ADD COLUMN IF NOT EXISTS deadline DATE;
ALTER TABLE public.rfqs ADD COLUMN IF NOT EXISTS created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.rfqs ADD COLUMN IF NOT EXISTS is_demo BOOLEAN DEFAULT FALSE;
ALTER TABLE public.rfqs ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS full_name TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS provinces TEXT[] DEFAULT '{}';
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS role TEXT DEFAULT 'supplier';
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS registration_complete BOOLEAN DEFAULT FALSE;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS onboarding_seen BOOLEAN DEFAULT FALSE;

UPDATE public.rfqs
SET
  buyer_org = COALESCE(buyer_org, buyer_name),
  industry = COALESCE(industry, category),
  provinces = CASE
    WHEN provinces IS NULL OR array_length(provinces, 1) IS NULL
      THEN ARRAY_REMOVE(ARRAY[province, region], NULL)
    ELSE provinces
  END,
  closing_date = COALESCE(closing_date, deadline::timestamptz),
  published_date = COALESCE(published_date, created_at),
  is_public = COALESCE(is_public, TRUE),
  quote_count = COALESCE(quote_count, 0);

CREATE UNIQUE INDEX IF NOT EXISTS rfqs_seed_title_buyer_org_key
  ON public.rfqs (title, buyer_org);

CREATE UNIQUE INDEX IF NOT EXISTS profiles_seed_email_key
  ON public.profiles (email)
  WHERE email IS NOT NULL;

ALTER TABLE public.rfqs ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'rfqs'
      AND policyname = 'Public users can read public open RFQs'
  ) THEN
    CREATE POLICY "Public users can read public open RFQs"
      ON public.rfqs
      FOR SELECT
      USING (is_public = TRUE AND status = 'open');
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'rfqs'
      AND policyname = 'Authenticated users can read RFQs'
  ) THEN
    CREATE POLICY "Authenticated users can read RFQs"
      ON public.rfqs
      FOR SELECT
      TO authenticated
      USING (TRUE);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'rfqs'
      AND policyname = 'Buyers can manage their own RFQs'
  ) THEN
    CREATE POLICY "Buyers can manage their own RFQs"
      ON public.rfqs
      FOR ALL
      TO authenticated
      USING (created_by = auth.uid() OR buyer_user_id = auth.uid())
      WITH CHECK (created_by = auth.uid() OR buyer_user_id = auth.uid());
  END IF;
END $$;
