-- Realistic South African procurement seed data for the RFQ marketplace.
-- Run create_rfqs_table.sql first.

ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS full_name TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS provinces TEXT[] DEFAULT '{}';
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS role TEXT DEFAULT 'supplier';
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS registration_complete BOOLEAN DEFAULT FALSE;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS onboarding_seen BOOLEAN DEFAULT FALSE;

CREATE UNIQUE INDEX IF NOT EXISTS profiles_seed_email_key
  ON public.profiles (email)
  WHERE email IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS rfqs_seed_title_buyer_org_key
  ON public.rfqs (title, buyer_org);

INSERT INTO public.profiles (
  id,
  email,
  full_name,
  business_name,
  industry,
  provinces,
  province,
  verification_status,
  role,
  registration_complete,
  onboarding_seen,
  created_at
) VALUES
  (gen_random_uuid(), 'procurement@ekurhuleni.gov.za', 'Naledi Mokoena', 'City of Ekurhuleni Metropolitan Municipality', 'Infrastructure', ARRAY['Gauteng'], 'Gauteng', 'Verified', 'buyer', TRUE, TRUE, NOW() - INTERVAL '18 days'),
  (gen_random_uuid(), 'supplychain@umngeni.gov.za', 'Thabo Zulu', 'uMngeni Local Municipality', 'Water and Sanitation', ARRAY['KwaZulu-Natal'], 'KwaZulu-Natal', 'Verified', 'buyer', TRUE, TRUE, NOW() - INTERVAL '16 days'),
  (gen_random_uuid(), 'scm@limpopohealth.gov.za', 'Rendani Ndlovu', 'Limpopo Department of Health', 'Healthcare', ARRAY['Limpopo'], 'Limpopo', 'Verified', 'buyer', TRUE, TRUE, NOW() - INTERVAL '14 days'),
  (gen_random_uuid(), 'tenders@eskom.co.za', 'Pieter Jacobs', 'Eskom Distribution Northern Cape', 'Energy', ARRAY['Northern Cape'], 'Northern Cape', 'Verified', 'buyer', TRUE, TRUE, NOW() - INTERVAL '12 days'),
  (gen_random_uuid(), 'procurement@westerncape.gov.za', 'Ayesha Davids', 'Western Cape Department of Infrastructure', 'Construction', ARRAY['Western Cape'], 'Western Cape', 'Verified', 'buyer', TRUE, TRUE, NOW() - INTERVAL '10 days'),
  (gen_random_uuid(), 'rfq@transnet.net', 'Sibongile Khumalo', 'Transnet Freight Rail', 'Logistics', ARRAY['Gauteng', 'KwaZulu-Natal'], 'Gauteng', 'Verified', 'buyer', TRUE, TRUE, NOW() - INTERVAL '8 days')
ON CONFLICT DO NOTHING;

INSERT INTO public.rfqs (
  title,
  description,
  scope,
  buyer_name,
  buyer_org,
  industry,
  provinces,
  bbbee_requirement,
  estimated_value_min,
  estimated_value_max,
  closing_date,
  published_date,
  status,
  require_csd,
  require_tax_clearance,
  require_vat,
  is_public,
  quote_count,
  category,
  province,
  region,
  budget,
  deadline,
  is_demo,
  created_at,
  updated_at
) VALUES
  (
    'Replacement of medium-voltage switchgear at municipal substations',
    'Supply, installation, testing, and commissioning of medium-voltage switchgear at two municipal substations in Ekurhuleni.',
    'Electrical works, protection relays, commissioning certificates, and handover training for municipal technicians.',
    'Naledi Mokoena',
    'City of Ekurhuleni Metropolitan Municipality',
    'Energy',
    ARRAY['Gauteng'],
    'Level 1-4',
    1800000,
    3200000,
    NOW() + INTERVAL '6 days',
    NOW() - INTERVAL '10 hours',
    'open',
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    3,
    'Energy',
    'Gauteng',
    'Gauteng',
    'R1,800,000 - R3,200,000',
    (NOW() + INTERVAL '6 days')::date,
    TRUE,
    NOW() - INTERVAL '10 hours',
    NOW()
  ),
  (
    'Water treatment plant chemical dosing system upgrade',
    'Upgrade the chemical dosing equipment at a municipal water treatment plant serving peri-urban communities.',
    'Mechanical supply, dosing pumps, calibration, safety documentation, and operator training.',
    'Thabo Zulu',
    'uMngeni Local Municipality',
    'Water and Sanitation',
    ARRAY['KwaZulu-Natal'],
    'Level 1-3',
    950000,
    1600000,
    NOW() + INTERVAL '9 days',
    NOW() - INTERVAL '1 day',
    'open',
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    4,
    'Water and Sanitation',
    'KwaZulu-Natal',
    'KwaZulu-Natal',
    'R950,000 - R1,600,000',
    (NOW() + INTERVAL '9 days')::date,
    TRUE,
    NOW() - INTERVAL '1 day',
    NOW()
  ),
  (
    'Supply of clinic backup power and inverter systems',
    'Provide backup power systems for rural clinics to support cold-chain and essential services during outages.',
    'Hybrid inverter supply, battery cabinets, installation, compliance certificates, and maintenance plan.',
    'Rendani Ndlovu',
    'Limpopo Department of Health',
    'Healthcare',
    ARRAY['Limpopo'],
    'Level 1-2',
    2400000,
    4100000,
    NOW() + INTERVAL '13 days',
    NOW() - INTERVAL '2 days',
    'open',
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    2,
    'Healthcare',
    'Limpopo',
    'Limpopo',
    'R2,400,000 - R4,100,000',
    (NOW() + INTERVAL '13 days')::date,
    TRUE,
    NOW() - INTERVAL '2 days',
    NOW()
  ),
  (
    'Distribution line vegetation management services',
    'Panel appointment for vegetation clearing along distribution servitudes in selected Northern Cape districts.',
    'Site clearing, safety files, environmental controls, and monthly progress reporting.',
    'Pieter Jacobs',
    'Eskom Distribution Northern Cape',
    'Energy',
    ARRAY['Northern Cape'],
    'Level 1-4',
    750000,
    2200000,
    NOW() + INTERVAL '3 days',
    NOW() - INTERVAL '6 hours',
    'open',
    TRUE,
    TRUE,
    FALSE,
    TRUE,
    6,
    'Energy',
    'Northern Cape',
    'Northern Cape',
    'R750,000 - R2,200,000',
    (NOW() + INTERVAL '3 days')::date,
    TRUE,
    NOW() - INTERVAL '6 hours',
    NOW()
  ),
  (
    'Framework contract for road marking and signage maintenance',
    'Road marking, reflective signage, and traffic-calming maintenance across provincial road assets.',
    'Labour, road-safe materials, traffic accommodation, quality assurance, and close-out reports.',
    'Ayesha Davids',
    'Western Cape Department of Infrastructure',
    'Construction',
    ARRAY['Western Cape'],
    'Level 1-4',
    3800000,
    7200000,
    NOW() + INTERVAL '21 days',
    NOW() - INTERVAL '4 days',
    'open',
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    5,
    'Construction',
    'Western Cape',
    'Western Cape',
    'R3,800,000 - R7,200,000',
    (NOW() + INTERVAL '21 days')::date,
    TRUE,
    NOW() - INTERVAL '4 days',
    NOW()
  ),
  (
    'Warehouse racking inspection and repair services',
    'Assess and repair industrial warehouse racking at a freight logistics hub.',
    'Structural inspections, repair materials, load signage, compliance certificates, and defect register.',
    'Sibongile Khumalo',
    'Transnet Freight Rail',
    'Logistics',
    ARRAY['Gauteng'],
    'Level 1-5',
    620000,
    980000,
    NOW() + INTERVAL '11 days',
    NOW() - INTERVAL '3 days',
    'open',
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    1,
    'Logistics',
    'Gauteng',
    'Gauteng',
    'R620,000 - R980,000',
    (NOW() + INTERVAL '11 days')::date,
    TRUE,
    NOW() - INTERVAL '3 days',
    NOW()
  ),
  (
    'Supply and installation of smart water meters',
    'Procurement of smart water meters with installation and data integration support for municipal billing.',
    'Meter supply, installation teams, device commissioning, training, and integration handover.',
    'Thabo Zulu',
    'uMngeni Local Municipality',
    'Water and Sanitation',
    ARRAY['KwaZulu-Natal'],
    'Level 1-3',
    3100000,
    5600000,
    NOW() + INTERVAL '16 days',
    NOW() - INTERVAL '20 hours',
    'open',
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    7,
    'Water and Sanitation',
    'KwaZulu-Natal',
    'KwaZulu-Natal',
    'R3,100,000 - R5,600,000',
    (NOW() + INTERVAL '16 days')::date,
    TRUE,
    NOW() - INTERVAL '20 hours',
    NOW()
  ),
  (
    'ICT helpdesk and endpoint support for regional offices',
    'Three-year support service for endpoint maintenance, service desk calls, and user support.',
    'Remote support, on-site callouts, asset register updates, monthly SLA reporting, and knowledge transfer.',
    'Rendani Ndlovu',
    'Limpopo Department of Health',
    'ICT',
    ARRAY['Limpopo'],
    'Level 1-4',
    1500000,
    2600000,
    NOW() + INTERVAL '18 days',
    NOW() - INTERVAL '5 days',
    'open',
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    2,
    'ICT',
    'Limpopo',
    'Limpopo',
    'R1,500,000 - R2,600,000',
    (NOW() + INTERVAL '18 days')::date,
    TRUE,
    NOW() - INTERVAL '5 days',
    NOW()
  ),
  (
    'Refurbishment of community hall ablution facilities',
    'Refurbish ablution blocks, plumbing, accessibility fittings, and finishes at two community halls.',
    'Minor building works, plumbing, tiling, fittings, waste disposal, and practical completion certificates.',
    'Naledi Mokoena',
    'City of Ekurhuleni Metropolitan Municipality',
    'Construction',
    ARRAY['Gauteng'],
    'Level 1-4',
    840000,
    1350000,
    NOW() + INTERVAL '5 days',
    NOW() - INTERVAL '30 hours',
    'open',
    TRUE,
    TRUE,
    FALSE,
    TRUE,
    5,
    'Construction',
    'Gauteng',
    'Gauteng',
    'R840,000 - R1,350,000',
    (NOW() + INTERVAL '5 days')::date,
    TRUE,
    NOW() - INTERVAL '30 hours',
    NOW()
  ),
  (
    'Panel for occupational health mobile screening services',
    'Mobile occupational health screening for field staff and depot-based teams.',
    'Medical screening, mobile clinic staffing, reporting, POPIA-aligned records handling, and appointment scheduling.',
    'Sibongile Khumalo',
    'Transnet Freight Rail',
    'Healthcare',
    ARRAY['Gauteng', 'KwaZulu-Natal'],
    'Level 1-4',
    1100000,
    1950000,
    NOW() + INTERVAL '24 days',
    NOW() - INTERVAL '7 days',
    'open',
    TRUE,
    TRUE,
    FALSE,
    TRUE,
    3,
    'Healthcare',
    'Gauteng',
    'Gauteng, KwaZulu-Natal',
    'R1,100,000 - R1,950,000',
    (NOW() + INTERVAL '24 days')::date,
    TRUE,
    NOW() - INTERVAL '7 days',
    NOW()
  ),
  (
    'Supply of PPE and arc-flash protective clothing',
    'Supply certified PPE and arc-flash protective clothing for electrical maintenance teams.',
    'Sizing, delivery, compliance certificates, replacement stock, and after-sales support.',
    'Pieter Jacobs',
    'Eskom Distribution Northern Cape',
    'Manufacturing',
    ARRAY['Northern Cape'],
    'Level 1-3',
    480000,
    900000,
    NOW() + INTERVAL '2 days',
    NOW() - INTERVAL '12 hours',
    'open',
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    8,
    'Manufacturing',
    'Northern Cape',
    'Northern Cape',
    'R480,000 - R900,000',
    (NOW() + INTERVAL '2 days')::date,
    TRUE,
    NOW() - INTERVAL '12 hours',
    NOW()
  ),
  (
    'Professional services for facilities condition assessments',
    'Condition assessments for schools and public facilities to support a provincial maintenance plan.',
    'Site inspections, photographic condition register, risk grading, cost estimates, and executive summary.',
    'Ayesha Davids',
    'Western Cape Department of Infrastructure',
    'Professional Services',
    ARRAY['Western Cape'],
    'Level 1-4',
    1200000,
    2100000,
    NOW() + INTERVAL '28 days',
    NOW() - INTERVAL '9 days',
    'open',
    TRUE,
    TRUE,
    FALSE,
    TRUE,
    2,
    'Professional Services',
    'Western Cape',
    'Western Cape',
    'R1,200,000 - R2,100,000',
    (NOW() + INTERVAL '28 days')::date,
    TRUE,
    NOW() - INTERVAL '9 days',
    NOW()
  )
ON CONFLICT DO NOTHING;
