begin;

alter table public.quotes
  add constraint quotes_id_rfq_id_key unique (id, rfq_id);

create table public.quote_evaluations (
  id bigint generated by default as identity primary key,
  rfq_id bigint not null references public.rfqs(id) on delete cascade,
  quote_id bigint not null,
  evaluator_id uuid not null references public.profiles(id) on delete restrict,
  price_score numeric(5,2) not null default 0 check (price_score between 0 and 20),
  compliance_score numeric(5,2) not null default 0 check (compliance_score between 0 and 20),
  delivery_score numeric(5,2) not null default 0 check (delivery_score between 0 and 20),
  experience_score numeric(5,2) not null default 0 check (experience_score between 0 and 20),
  locality_score numeric(5,2) not null default 0 check (locality_score between 0 and 20),
  total_score numeric(6,2) not null default 0 check (total_score between 0 and 100),
  evaluation_notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint quote_evaluations_quote_rfq_fkey
    foreign key (quote_id, rfq_id) references public.quotes(id, rfq_id) on delete cascade,
  constraint quote_evaluations_quote_evaluator_key unique (quote_id, evaluator_id)
);

create index quote_evaluations_rfq_id_idx on public.quote_evaluations(rfq_id);
create index quote_evaluations_quote_id_idx on public.quote_evaluations(quote_id);
create index quote_evaluations_evaluator_id_idx on public.quote_evaluations(evaluator_id);

create trigger quote_evaluations_set_updated_at
before update on public.quote_evaluations
for each row execute function public.set_updated_at();

alter table public.quote_evaluations enable row level security;
revoke all on public.quote_evaluations from anon;
grant select, insert, update, delete on public.quote_evaluations to authenticated;
grant usage, select on sequence public.quote_evaluations_id_seq to authenticated;

create policy quote_evaluations_select
  on public.quote_evaluations for select to authenticated
  using (
    public.is_admin()
    or exists (
      select 1 from public.rfqs
      where rfqs.id = quote_evaluations.rfq_id
        and rfqs.created_by = (select auth.uid())
    )
  );

create policy quote_evaluations_insert
  on public.quote_evaluations for insert to authenticated
  with check (
    evaluator_id = (select auth.uid())
    and (
      public.is_admin()
      or exists (
        select 1 from public.rfqs
        where rfqs.id = quote_evaluations.rfq_id
          and rfqs.created_by = (select auth.uid())
      )
    )
  );

create policy quote_evaluations_update
  on public.quote_evaluations for update to authenticated
  using (
    evaluator_id = (select auth.uid())
    and (
      public.is_admin()
      or exists (
        select 1 from public.rfqs
        where rfqs.id = quote_evaluations.rfq_id
          and rfqs.created_by = (select auth.uid())
      )
    )
  )
  with check (
    evaluator_id = (select auth.uid())
    and (
      public.is_admin()
      or exists (
        select 1 from public.rfqs
        where rfqs.id = quote_evaluations.rfq_id
          and rfqs.created_by = (select auth.uid())
      )
    )
  );

create policy quote_evaluations_delete
  on public.quote_evaluations for delete to authenticated
  using (
    evaluator_id = (select auth.uid())
    and (
      public.is_admin()
      or exists (
        select 1 from public.rfqs
        where rfqs.id = quote_evaluations.rfq_id
          and rfqs.created_by = (select auth.uid())
      )
    )
  );

drop policy if exists po_select on public.purchase_orders;
create policy po_select
  on public.purchase_orders for select to authenticated
  using (
    supplier_id = (select auth.uid())
    or public.is_admin()
    or exists (
      select 1 from public.rfqs
      where rfqs.id = purchase_orders.rfq_id
        and rfqs.created_by = (select auth.uid())
    )
  );

commit;
